#!/usr/bin/env bash
set -euo pipefail

echo "TON RLDP-HTTP-Proxy Setup Helper"
echo "================================"
echo ""

if [ ! -f docker-compose.yml ]; then
    echo "Error: Run this script from the directory containing docker-compose.yml"
    exit 1
fi

# 1. Generate keys if keyring is empty or missing
if [ ! -d ./keyring ] || [ -z "$(ls -A ./keyring)" ]; then
    echo "Generating new ADNL keypair..."
    mkdir -p ./keyring

    # Use docker to run generator (keeps everything consistent)
    docker run --rm -it \
      -v "$(pwd)/keyring:/ton-proxy/keyring" \
      tonnamespace/rldp-http-proxy:latest --generate-keys

    echo ""
    echo "Key generation complete."
    echo "Look for the base64 ADNL address in the output above (something like xjank...)"
    echo ""
    read -p "Paste the ADNL address here: " adnl_addr

    if [ -z "$adnl_addr" ]; then
        echo "No address provided. Exiting."
        exit 1
    fi
else
    echo "Existing keyring found. Skipping generation."
    read -p "Enter your SERVER_ADNL_ADDRESS (or press Enter to skip): " adnl_addr
fi

# 2. Create .env file
cat > main.env << EOF
# Generated by prepare.sh - do not commit to git!
SERVER_PUBLIC_IP=$(curl -s ipinfo.io/ip || echo "your.public.ip.here")
SERVER_ADNL_ADDRESS=$adnl_addr
PORT=8080
ADNL_PORT=3333
VERBOSITY=DEBUG
CONFIG_PATH=/ton-proxy/global.config.json
EOF

echo ""
echo "Created/updated .env file with your settings."
echo "Review and edit it if needed (especially SERVER_PUBLIC_IP)."
echo ""
echo "Next steps:"
echo "1. docker compose up -d"
echo "2. Check logs: docker compose logs -f"
echo ""
echo "Done! Happy proxying :)"
